### ISSUE TITLE
Package libqofono and  voicecall

### ISSUE THREAD

**Issue by bhush9** [blue-systems/pm-arch#4]

**Comment by bhush9** [comment]
beb05ef62c3d01cc2cc0162cb5f63500ad8cf109 and http://arch.pangea.pub/plasma-mobile/x86_64/libqofono-qt5-0.80.r2.d9a8603-1-x86_64.pkg.tar.xz

**Comment by bhush9** [comment]
Voicecall is not required.

**Comment by bhush9** [comment]
libqofono is not installed on ISO as it is useless anyway.. (one can't dial)

**Comment by mck182** [comment]
Why is it that you cannot dial? Do you have ofono and telepathy-ofono (the one from lunchpad) installed?

EDIT: This one -- https://code.launchpad.net/telepathy-ofono

**Comment by bhush9** [comment]
well, one doesn't have sim card on desktop and/or laptop.. and yes I've them packaged.
