### ISSUE TITLE
panels are nice, but app icons + favorites bar are still huge

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm-arch#7]

**Comment by bhush9** [comment]
http://commits.kde.org/plasma-phone-components/38a3a7c99cd9b15dd421013b445c31678e66e28f

Fixed in git, next ISO will have this patch.

**Comment by bhush9** [comment]
Also MoKCI job triggered for it.. so you can update plasma-phone-components on kubuntu and test on it too..
